### PR TITLE
Move checks for Page.base_form_class / get_form_class to wagtailadmin

### LINKED ISSUE #2428: Error on new installation without custom page models
I think this is related to #2267. I came across this problem two days ago with wagtail 1.4.1 and the patch by @timheap applied locally and it persists with wagtail 1.4.2.

Currently it is not possible to start with a new wagtail project where only the base ``Page`` class is present. Trying to run any of the management commands (like ``python manage.py migrate``) produces the following error:

```
File "/my/path/lib/python3.3/site-packages/wagtail/wagtailcore/models.py", line 561, in check
    if not issubclass(cls.base_form_class, WagtailAdminPageForm):
AttributeError: type object 'Page' has no attribute 'base_form_class'
```

After adding own page models and migrations all works fine.

### PR DESCRIPTION
**Pull request by gasman**
Fixes #2428

The `Page.check` method was validating the base_form_class / get_form_class methods, which aren't really the concern of wagtailcore (and are only defined if wagtailadmin.edit_handlers has been imported). These checks have now been moved to wagtailadmin.

(Have also fixed an incorrect use of `ugettext` at the class level in wagtailadmin.forms that prevented it from being imported in wagtailadmin.checks - although in the end I've had to put the imports in the check methods anyway, due to some other weirdness with import order)

### CODE REVIEW

**Comment by kaedroho** [comment]
Testing locally, still getting the error:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/karl/projects/iss2428/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/karl/projects/iss2428/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/karl/projects/iss2428/venv/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/karl/projects/iss2428/venv/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/karl/projects/iss2428/venv/lib/python3.5/site-packages/django/core/management/commands/check.py", line 51, in handle
    include_deployment_checks=include_deployment_checks,
  File "/home/karl/projects/iss2428/venv/lib/python3.5/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/karl/projects/iss2428/venv/lib/python3.5/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/karl/projects/wagtail/wagtail/wagtailadmin/checks.py", line 43, in base_form_class_check
    if not issubclass(cls.base_form_class, WagtailAdminPageForm):
AttributeError: type object 'Page' has no attribute 'base_form_class'
```

**Comment by gasman** [comment]
Ah, looks like it's only working on Django 1.9... 1.8 must do its imports differently, meaning that edit_handlers doesn't get implicitly imported. (Meanwhile, Travis is failing because the updated test encounters the "CSS is missing" warning that's been silently ignored up to now - grr...)

**Comment by gasman** [comment]
Fixed by importing edit_handlers inside wagtailadmin.models. Not the nicest fix in the world, but I'd prefer not to make any more dramatic changes for a 1.4.x fix...

**Comment by kaedroho** [comment]
Merged in db1e4aad1585a66451ae6e7de8f0af7ad84df054 (``master``) and 5976e66cfbc0e796b5e4b343706466df849088bb (``stable/1.4.x``). Thanks!
