### ISSUE TITLE
Frontend cache invalidator HTTP Backend doesn't work on Python 2

### ISSUE THREAD

**Issue by mixxorz** [torchbox/wagtail#1924]
Passing `method` as a keyword argument does not work on Python < 3.3. It gives an error:

```
__init__() got an unexpected keyword argument 'method'
```

```
request = Request(
            url=urlunparse([
                self.cache_scheme,
                self.cache_netloc,
                url_parsed.path,
                url_parsed.params,
                url_parsed.query,
                url_parsed.fragment
            ]),
            headers={
                'Host': host,
                'User-Agent': 'Wagtail-frontendcache/' + __version__
            },
            method='PURGE'
        )
```
I can work around this issue in my project by specifying a custom backend. I'll have to subclass `Request` to override its `get_method` method.

Additionally, the test suite does not explicitly test the invalidator backends. That's understandable though. Testing network requests isn't easy.
