### PR TITLE
Clusterable redirects

### PR DESCRIPTION
**Pull request by HalcyonChimera**
### Thanks for contributing to Wagtail! 🎉

Please review [the contributor guidelines](http://docs.wagtail.io/en/latest/contributing/index.html) and confirm that [the tests pass](http://docs.wagtail.io/en/latest/contributing/developing.html#testing) in case of Python changes.

### CODE REVIEW

**Comment by gasman** [comment]
Hi @HalcyonChimera - please can you explain the purpose of this change?

**Comment by HalcyonChimera** [comment]
I have the requirement of versioning the actual urls that point to a page; i.e if a page is moved, then a redirect is automatically created. With this I was able to use an InlinePanel so that redirects pointing at that page can be added/changed/removed from a given Page's promote panel. With only a ForeignKey, there is an error <PageModel> has no attribute 'redirect_set'.

**Comment by gasman** [comment]
Thanks for the clarification! I have a feeling that this change will cause broken behaviour for existing users, though:

* A user creates and saves a page (this will result in an empty list of redirects being saved within the PageRevision record, regardless of whether the admin form includes an InlinePanel for redirects)
* They then set up redirects through the Settings -> Redirects area (which creates the redirect records immediately)
* They make further edits to the page, and publish it (- the edits are based on the most recent PageRevision record, which has an empty list of redirects - and so publishing the page will cause the existing redirects to be deleted)

This is probably a general issue that would affect any model that's editable in two places - as an independent model, and through an InlinePanel. In this case you're probably better off setting up an independent "inline redirect" model that works separately to the `wagtailredirects` module, with its own middleware.

**Comment by HalcyonChimera** [comment]
The issue with having it separate is that it will be confusing for editors to have two places to look in order to determine the redirects that apply to a given page. Maybe we should compare the revision with other redirects created since it was last saved and try to replay the changes  into the revision record before it is saved and throw growls that say 'there are conflicting redirects'?

I feel like duplicating the entire redirect functionality here isn't necessarily the best use of time, and this is a feature I think it makes a lot of sense to provide; there is already the ability to change the slug of a page in the promote panel, for example. Having the ability to control those changes in the same location has a certain ergonomics to it.

What other edge cases might there be in terms of migrations and or chronologically dependent actions?

**Comment by gasman** [comment]
The issue here is really that there are lots of different uses for redirects: preserving links when a page is moved, replacing an older site built on a different CMS, providing short/memorable links, doing tracking/analytics, providing a fixed link to changing resources (e.g. a monthly publication that has a redirect pointing to 'latest issue') and probably lots more that I haven't thought of. For some of those uses, it makes sense to tie redirects to a page's revisioning / publishing workflow; for others, it would be very much a backward step.

The current behaviour of wagtailredirects isn't the best fit for everything (indeed, people have created their own alternatives to it - see #655 for example), but existing users are relying on it to continue working in the same way, and I'd be very reluctant to make such a sweeping change to an established part of Wagtail.
