### ISSUE TITLE
Error with django-overextends with Django 1.8

### ISSUE THREAD

**Issue by chadsaun** [torchbox/wagtail#1513]
I'm getting an error with django-overextends using Django 1.8.  I've installed overextends with pip.

    django.template.base.InvalidTemplateLibrary: ImportError raised loading overextends.templatetags.overextends_tags: cannot import name find_template_loader

Has anyone been able to get django-overextends to work with Django 1.8?

**Comment by gasman** [comment]
Looking at https://github.com/stephenmcd/django-overextends/issues/16 and the commit history https://github.com/stephenmcd/django-overextends/commits/master, it appears that Django 1.8 support is in progress (or is possibly complete, but hasn't made it into a release yet).

Closing as this isn't something that we can provide support for (although if no fixed version appears soon, we'll have to come up with an alternative method for custom branding...)

**Comment by mattots** [comment]
Just to chip in on this - we're using Django 1.8 and found that importing the latest version of django-overextends from Github rather than PyPi works fine.
